# This is a basic workflow to help you get started with Actions

name: Sync from

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the script-sync-from branch
#   push:
#     branches: [ script-sync-from ]
#   pull_request:
#     branches: [ script-sync-from ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
              ref: script-sync-from
              path: scripts   
      - name: debug print
        run: dir .
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - uses: actions/checkout@v2
        with: 
              ref: registry
              path: .

        # 缓存yarn
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: |
          cd .\scripts
          yarn
          cd ..
      # Runs a set of commands using the runners shell
      - name: sync registry
        run: |
          node ./scripts/sync.js
          
      - name: commit changes
        run: |
          git config --local user.email "bot@edgeless.top"
          git config --local user.name "SyncBot"
          git commit -m "Sync from source" -a
          
      - uses: actions-go/push@v1
        with:  
              force: true
              ref: registry
              token: ${{ secrets.GITHUB_TOKEN }}
