# This is a basic workflow to help you get started with Actions

name: Sync from

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the script-sync-from branch
#   push:
#     branches: [ script-sync-from ]
#   pull_request:
#     branches: [ script-sync-from ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
              ref: script-sync-from  
      - name: debug print
        run: dir .
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - uses: actions/checkout@v2
        with: 
              ref: registry
              path: .\mirrors

        # 缓存yarn
      - name: sync registry
        run: .\setup.bat

      - uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: registry
            directory: .\mirrors
